image: docker:git
services:
  - docker:dind
before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
stages:
  - test
  - build
  - development
test:
  stage: test
  script:
    - docker build -t tests -f Tests.Dockerfile .
    - docker run tests
  tags:
    - docker
build:
  stage: build
  script:
    - docker build -t excel-platform/api:latest -f Production.Dockerfile .
  tags:
    - docker
  only:
    - master@excel-mec/excel-accounts/Excel-Accounts-Backend
