image: docker:git
services:
  - docker:dind
before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
stages:
  - build
  - development
build:
  stage: build
  script:
    - cd API
    - docker build -t $DOCKER_IMAGE_NAME:latest -f $DOCKER_FILE_PATH .
  tags:
    - docker
