image: docker:git
variables:
  - upstream: master@excel-mec/excel-accounts/Excel-Accounts-Backend
services:
  - docker:dind
before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  only:
    - upstream
stages:
  - test
  - build
  - development
test:
  stage: test
  script:
    - docker build -t tests -f Tests.Dockerfile .
    - docker run tests
  tags:
    - docker
build:
  stage: build
  script:
    - docker build -t excel-platform/api:latest -f Development.Dockerfile .
  tags:
    - docker
  only:
    - upstream
